site_name: Salesforce Pure Charity App Documentation
pages:
- Home: index.md
- Changelog: changelog.md
- Mapping:
  - Donations: mapping/donations.md
  - Direct donations: mapping/direct_donations.md
  - Direct donations to specific categories: mapping/donation_categories.md
  - Fundraisers: mapping/fundraisers.md
  - Sponsorships Programs: mapping/sponsorship_programs.md
  - Sponsorships: mapping/sponsorships.md
  - Trips: mapping/trips.md
  - Trip Registrations: mapping/registrations.md
  - Users: mapping/users.md
  - Mission passport: mapping/mission_passport.md
  - Giving Circles: mapping/giving_circles.md
  - Adjustments: mapping/adjustments.md

